// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBMAvwznSKmZDKbKyAf8LmzItcyGEtk0U',
    appId: '1:802202577651:web:65e180352aa6b2b9b9a586',
    messagingSenderId: '802202577651',
    projectId: 'todopoints2',
    authDomain: 'todopoints2.firebaseapp.com',
    storageBucket: 'todopoints2.firebasestorage.app',
    measurementId: 'G-LHMPTH6KKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtPOFj_6bQIx0YMxoN0lUW1x01Wttp1LI',
    appId: '1:802202577651:android:9c4c36dbed3d208db9a586',
    messagingSenderId: '802202577651',
    projectId: 'todopoints2',
    storageBucket: 'todopoints2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDncDSujELHX_4OXm8W7xyufa89O_VbKDE',
    appId: '1:802202577651:ios:4ae62cd48864ee6eb9a586',
    messagingSenderId: '802202577651',
    projectId: 'todopoints2',
    storageBucket: 'todopoints2.firebasestorage.app',
    iosBundleId: 'com.example.todopoints2',
  );
}
